site_name: mpljourney
site_url: https://JosephBARBIERDARNAL.github.io/mpljourney/
repo_url: https://github.com/JosephBARBIERDARNAL/mpljourney

theme:
  name: material
  custom_dir: overrides
  features:
    - content.code.copy
    - navigation.path
    - navigation.tabs
  icon:
    repo: fontawesome/brands/github

plugins:
  - search

nav:
  - Home: index.md

extra_css:
  - stylesheets/style.css

markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
